/**
 * @file			controlBox.h
 *	@author		Nahum Budin
 *	@date		5-Dec-2025
 *	@version	1.1
 *					1. Add I2C control defines.
 *
 *	@brief		MIDI control box API
 *
 *History:\n
 *		version 1.0		6-Jul-2024: First version
 *
 *	Based on libAdjHeartModSynth_1.h Ver 1.3 9-Jan-2021
 */

#pragma once

/* Sysex Vendor ID - TEMP TODO: */
#define _MIDI_CONTROL_BOX_SYSEX_VENDOR_ID_0 0
#define _MIDI_CONTROL_BOX_SYSEX_VENDOR_ID_1 0x35
#define _MIDI_CONTROL_BOX_SYSEX_VENDOR_ID_2 0x56
#define _MIDI_CONTROL_BOX_SYSEX_VENDOR_ID_2CB 0x57 // Control Board

/* UART Interface Controls IDs */
#define _CONTROL_PUSHBUTTON_BLUE_BLACK		0x00
#define _CONTROL_PUSHBUTTON_BLUE_GREEN		0x01
#define _CONTROL_PUSHBUTTON_BLUE_RED		0x02
#define _CONTROL_PUSHBUTTON_BLUE_BLUE		0x03
#define _CONTROL_PUSHBUTTON_BLUE_WHITE		0x04
#define _CONTROL_PUSHBUTTON_BLUE_YELLOW		0x05
#define _CONTROL_PUSHBUTTON_ORANGE_BLACK	0x06
#define _CONTROL_PUSHBUTTON_ORANGE_GREEN	0x07
#define _CONTROL_PUSHBUTTON_ORANGE_RED		0x08
#define _CONTROL_PUSHBUTTON_ORANGE_BLUE		0x09
#define _CONTROL_PUSHBUTTON_ORANGE_WHITE	0x0a
#define _CONTROL_PUSHBUTTON_ORANGE_YELLOW	0x0b

#define _CONTROL_FUNCTION_PUSHBUTTON_UP		0x0d
#define _CONTROL_FUNCTION_PUSHBUTTON_REDOO	0x0e
#define _CONTROL_FUNCTION_PUSHBUTTON_ENTER	0x0f

#define _CONTROL_ENCODER_BLUE_PURPLE		0x10
#define _CONTROL_ENCODER_BLUE_GREEN			0x11
#define _CONTROL_ENCODER_BLUE_RED			0x12
#define _CONTROL_ENCODER_BLUE_BLUE			0x13
#define _CONTROL_ENCODER_BLUE_WHITE			0x14
#define _CONTROL_ENCODER_BLUE_YELLOW		0x15
#define _CONTROL_ENCODER_ORANGE_PURPLE		0x16
#define _CONTROL_ENCODER_ORANGE_GREEN		0x17
#define _CONTROL_ENCODER_ORANGE_RED			0x18
#define _CONTROL_ENCODER_ORANGE_BLUE		0x19
#define _CONTROL_ENCODER_ORANGE_WHITE		0x1a
#define _CONTROL_ENCODER_ORANGE_YELLOW		0x1b

#define _CONTROL_ENCODER_PUSHBUTTON_BLUE_BLACK		0x20
#define _CONTROL_ENCODER_PUSHBUTTON_BLUE_GREEN		0x21
#define _CONTROL_ENCODER_PUSHBUTTON_BLUE_RED		0x22
#define _CONTROL_ENCODER_PUSHBUTTON_BLUE_BLUE		0x23
#define _CONTROL_ENCODER_PUSHBUTTON_BLUE_WHITE		0x24
#define _CONTROL_ENCODER_PUSHBUTTON_BLUE_YELLOW		0x25
#define _CONTROL_ENCODER_PUSHBUTTON_ORANGE_BLACK	0x26
#define _CONTROL_ENCODER_PUSHBUTTON_ORANGE_GREEN	0x27
#define _CONTROL_ENCODER_PUSHBUTTON_ORANGE_RED		0x28
#define _CONTROL_ENCODER_PUSHBUTTON_ORANGE_BLUE		0x29
#define _CONTROL_ENCODER_PUSHBUTTON_ORANGE_WHITE	0x2a
#define _CONTROL_ENCODER_PUSHBUTTON_ORANGE_YELLOW	0x2b

#define _CONTROL_SLIDER_BLUE_BLACK					0x30
#define _CONTROL_SLIDER_BLUE_GRAY					0x31
#define _CONTROL_SLIDER_BLUE_RED					0x32
#define _CONTROL_SLIDER_BLUE_BLUE					0x33
#define _CONTROL_SLIDER_BLUE_WHITE					0x34
#define _CONTROL_SLIDER_BLUE_YELLOW					0x35
#define _CONTROL_SLIDER_ORANGE_BLACK				0x36
#define _CONTROL_SLIDER_ORANGE_GRAY					0x37
#define _CONTROL_SLIDER_ORANGE_RED					0x38
#define _CONTROL_SLIDER_ORANGE_BLUE					0x39
#define _CONTROL_SLIDER_ORANGE_WHITE				0x3a
#define _CONTROL_SLIDER_ORANGE_YELLOW				0x3b

#define _CONTROL_YELLOW_LED							0x3e
#define _CONTROL_GREEN_LED							0x3f

/* I2C Interface Controls IDs */
#define _I2C_CONTROL_ENCODER_1 0x40
#define _I2C_CONTROL_ENCODER_2 0x41
#define _I2C_CONTROL_ENCODER_3 0x42
#define _I2C_CONTROL_ENCODER_4 0x43
#define _I2C_CONTROL_ENCODER_5 0x44
#define _I2C_CONTROL_ENCODER_6 0x45
#define _I2C_CONTROL_ENCODER_7 0x46
#define _I2C_CONTROL_ENCODER_8 0x47
#define _I2C_CONTROL_ENCODER_9 0x48
#define _I2C_CONTROL_ENCODER_10 0x49
#define _I2C_CONTROL_ENCODER_11 0x4a
#define _I2C_CONTROL_ENCODER_12 0x4b
#define _I2C_CONTROL_ENCODER_13 0x4c
#define _I2C_CONTROL_ENCODER_14 0x4d
#define _I2C_CONTROL_ENCODER_15 0x4e
#define _I2C_CONTROL_ENCODER_16 0x4f

#define _I2C_CONTROL_ENCODER_SCROLL 0x50
#define _I2C_CONTROL_ENCODER_MASTER_VOLUME 0x51

#define _I2C_CONTROL_SLIDER_1 0x60
#define _I2C_CONTROL_SLIDER_2 0x61
#define _I2C_CONTROL_SLIDER_3 0x62
#define _I2C_CONTROL_SLIDER_4 0x63
#define _I2C_CONTROL_SLIDER_5 0x64
#define _I2C_CONTROL_SLIDER_6 0x65
#define _I2C_CONTROL_SLIDER_7 0x66
#define _I2C_CONTROL_SLIDER_8 0x67
#define _I2C_CONTROL_SLIDER_9 0x68
#define _I2C_CONTROL_SLIDER_10 0x69
#define _I2C_CONTROL_SLIDER_11 0x6a
#define _I2C_CONTROL_SLIDER_12 0x6b
#define _I2C_CONTROL_SLIDER_13 0x6c
#define _I2C_CONTROL_SLIDER_14 0x6d
#define _I2C_CONTROL_SLIDER_15 0x6e
#define _I2C_CONTROL_SLIDER_16 0x6f

#define _I2C_CONTROL_ENCODER_PUSHBUTTON_1 0x70
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_2 0x71
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_3 0x72
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_4 0x73
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_5 0x74
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_6 0x75
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_7 0x76
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_8 0x77
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_9 0x78
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_10 0x79
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_11 0x7a
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_12 0x7b
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_13 0x7c
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_14 0x7d
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_15 0x7e
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_16 0x7f

#define _I2C_CONTROL_ENCODER_PUSHBUTTON_SCROLL 0x53
#define _I2C_CONTROL_ENCODER_PUSHBUTTON_MASTER_VOLUME 0x54

#define _I2C_CONTROL_YELLOW_LED 0x55
#define _I2C_CONTROL_GREEN_LED 0x57

#define _I2C_CONTROL_PUSHBUTTON_OK 0x58
#define _I2C_CONTROL_PUSHBUTTON_UP 0x59
#define _I2C_CONTROL_PUSHBUTTON_DOWN 0x5a
#define _I2C_CONTROL_PUSHBUTTON_LEFT 0x5b
#define _I2C_CONTROL_PUSHBUTTON_RIGHT 0x5c

// MIDI events for I2C control box control board buttons pressed
#define _I2C_CONTROL_PUSHBUTTON_NONE_PRESSED	0x1f
#define _I2C_CONTROL_PUSHBUTTON_OK_PRESSED		0x1e
#define _I2C_CONTROL_PUSHBUTTON_UP_PRESSED		0x1d
#define _I2C_CONTROL_PUSHBUTTON_DOWN_PRESSED	0x1b
#define _I2C_CONTROL_PUSHBUTTON_LEFT_PRESSED	0x17
#define _I2C_CONTROL_PUSHBUTTON_RIGHT_PRESSED	0x0f

