/**
* @file			hammondOrgan.h
*	@author		Nahum Budin
*	@date		21-Apr-2026
*	@version	1.0
*	
*	@brief		Provides the Hammond Organ Instrument related API
*	
*/

#pragma once

#include "synthesizer.h"

#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_1 10
#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_2 11
#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_3 12
#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_4 13
#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_5 14
#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_6 15
#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_7 16
#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_8 17
#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_9 18

#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_MAX 8
#define _HAMMOND_ORGAN_DRAWBAR_LEVEL_MIN 0

#define _HAMMOND_ORGAN_DETUNE_OCTAVE 100
#define _HAMMOND_ORGAN_DETUNE_SEMITONES 110
#define _HAMMOND_ORGAN_DETUNE_CENTS 120

#define _HAMMOND_ORGAN_SQUARE_WAVE_ENABLE 130

#define _HAMMOND_ORGAN_PERCUSSION_MODE 140

#define _HAMMOND_ORGAN_PERCUSION_MODE_OFF				0
#define _HAMMOND_ORGAN_PERCUSION_MODE_2ND_SOFT_SLOW		1
#define _HAMMOND_ORGAN_PERCUSION_MODE_2ND_SOFT_FAST		2
#define _HAMMOND_ORGAN_PERCUSION_MODE_2ND_NORM_SLOW		3
#define _HAMMOND_ORGAN_PERCUSION_MODE_2ND_NORM_FAST		4
#define _HAMMOND_ORGAN_PERCUSION_MODE_3RD_SOFT_SLOW		5
#define _HAMMOND_ORGAN_PERCUSION_MODE_3RD_SOFT_FAST		6
#define _HAMMOND_ORGAN_PERCUSION_MODE_3RD_NORM_SLOW		7
#define _HAMMOND_ORGAN_PERCUSION_MODE_3RD_NORM_FAST		8

#define _HAMMOND_ORGAN_LESLIE_SPEED 150
#define _HAMMOND_ORGAN_LESLIE_LEVEL 160

#define _HAMMOND_ORGAN_SEND_FILTER_1 170
#define _HAMMOND_ORGAN_SEND_FILTER_2 180


int mod_synth_set_hammond_organ_param_value(int mod_id, int param_id, int value);
int mod_synth_get_hammond_organ_param_value(int mod_id, int param_id);
